CREATE TABLE currency_rate (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency VARCHAR(3) NOT NULL,
    quote_currency VARCHAR(3) NOT NULL,
    rate DECIMAL(38,20) NOT NULL,
    fetched_at TIMESTAMP NOT NULL
);