spring:
  application:
    name: currency-rates

  datasource:
    url: jdbc:h2:file:./.h2/currencydb;MODE=PostgreSQL;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
        generate_statistics: true
    show-sql: true

  flyway:
    enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

rates:
  base-url: https://api.exchangerate.host
  latest-path: /live
  fetch-cron: 0 * * * * *
  access-key: 9582f01c1f532c407454d65eea929d73

logging:
  level:
    root: INFO
    com.example.currencyrates: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: DEBUG
